name:  Kuaishou

on:
    workflow_dispatch:
    schedule:
        - cron: "1 0,8-18 * * *"
    watch:
        types: [started]

jobs:
  run-coupons: # 任务名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '14'
          
      - name: "快手" 
        run: |
          npm install
          npm install parse
          npm install got
          npm install xmlhttprequest
          npm install tough-cookie       
          node Kuaishou0509.js
          env:
              ksjsbCookie: ${{ secrets.KUAISHOU }}
