name:  Kuaishou
on:
    workflow_dispatch:
    schedule:
        - cron: "1 0,8-18 * * *"
    watch:
        types: [started]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 使用 node:10

    - name: use Node.js 10.x

      uses: actions/setup-node@v1

      with:

        node-version: 10.x

    # npm install

    - name: npm install and do sign

        env:
              ksjsbCookie: ${{ secrets.KUAISHOU }}
      run: |

        npm install

          node Kuaishou0509.js
          
