name: write
on:
    workflow_dispatch:
    watch:
        types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: 订阅脚本 #订阅脚本
      env: 
        GHCOOKIE: ${{ secrets.GHCOOKIE }} # secrets_id 提供
      run: | 
        python DingYue.py
    - name: Commit #上传新的refresh_token到仓库
      run: |
        git config --global user.email AutoupdateRobot@email.com
        git config --global user.name AutoupdateRobot
        git add .
        git commit -m "update new Node.txt" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
